name : my-first-action

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: Execute Shell script
        run: |
             chmod +x test-script.sh
             ./test-script.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: test-file
          path: test.txt
            
  second_job:
    needs: [first_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: List of files
        run: |
            ls
            sleep 600s

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
            name: test-file
      - name: read file
        run: cat test.txt

    
