name : my-first-action

on : push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: sleep step
        run: sleep 40

      - name: Execute Shell script
        run: |
             chmod +x test-script.sh
             ./test-script.sh
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: List of files
        run: ls

      - name: read file
        run: cat README.md
