name : matrix-workflow

on: push
concurrency: 
    group: production-step
    cancel-in-progress: true
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        images: [hello-world]
    runs-on: ${{matrix.os}}
    steps:
      - name: Running images ${{matrix.images}}
        run: docker run ${{matrix.images}}